//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationVoiture.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class client
    {
        public client()
        {
            this.reservations = new HashSet<reservation>();
        }
    
        public int clientID { get; set; }
        public string password { get; set; }
        public string nom { get; set; }
        public System.DateTime date_enregistrement { get; set; }
        public string telephone { get; set; }
        public string adresse_client { get; set; }
        public Nullable<long> num_carte_credit { get; set; }
        public string permis_conduire_num { get; set; }
        public string assurance { get; set; }
        public string courriel { get; set; }
        public string prenom { get; set; }
    
        public virtual ICollection<reservation> reservations { get; set; }
    }
}
