//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationVoiture.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class employe
    {
        public employe()
        {
            this.reservations = new HashSet<reservation>();
            this.locations = new HashSet<location>();
        }
    
        public int employeID { get; set; }
        public string password { get; set; }
        public string nom { get; set; }
        public string fonction { get; set; }
        public System.DateTime date_embauche { get; set; }
        public Nullable<float> salaire_horaire { get; set; }
        public int succursaleID { get; set; }
    
        public virtual ICollection<reservation> reservations { get; set; }
        public virtual ICollection<location> locations { get; set; }
    }
}
