//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationVoiture.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class fabriquant
    {
        public fabriquant()
        {
            this.vehicules = new HashSet<vehicule>();
        }
    
        public int fabriquantID { get; set; }
        public string nom_fabriquant { get; set; }
        public string addresse_service { get; set; }
        public string telephone_service { get; set; }
    
        public virtual ICollection<vehicule> vehicules { get; set; }
    }
}
