//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationVoiture.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class location
    {
        public int locationID { get; set; }
        public System.DateTime date_debut { get; set; }
        public System.DateTime date_fin { get; set; }
        public Nullable<int> reservationID { get; set; }
        public int vehiculeID { get; set; }
        public int employeID { get; set; }
    
        public virtual employe employe { get; set; }
        public virtual reservation reservation { get; set; }
        public virtual vehicule vehicule { get; set; }
    }
}
