//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationVoiture.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class modele
    {
        public modele()
        {
            this.vehicules = new HashSet<vehicule>();
        }
    
        public int modeleID { get; set; }
        public int typeID { get; set; }
        public string nom_modele { get; set; }
        public Nullable<int> nb_place { get; set; }
        public Nullable<float> consommation_carburant { get; set; }
        public string transmission { get; set; }
    
        public virtual type type { get; set; }
        public virtual ICollection<vehicule> vehicules { get; set; }
    }
}
