//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LocationVoiture.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class succursale
    {
        public succursale()
        {
            this.reservations = new HashSet<reservation>();
            this.vehicules = new HashSet<vehicule>();
        }
    
        public int succursaleID { get; set; }
        public string addresse { get; set; }
        public string telephone { get; set; }
        public string courriel { get; set; }
        public string nom { get; set; }
    
        public virtual ICollection<reservation> reservations { get; set; }
        public virtual ICollection<vehicule> vehicules { get; set; }
    }
}
